export const amenities = {
  shortlet: [
    "Pet-friendly",
    "Dishwasher",
    "TV",
    "WiFi",
    "Sauna",
    "Crib",
    "No smoking",
    "Kitchen",
    "Family-friendly",
    "Grill",
    "Hairdryer",
    "Coffee machine",
    "Kettle",
    "Toaster",
    "Heating",
    "Fridge",
    "Radio",
    "Fitness",
    "Ocean view",
    "CD player",
    "Balcony",
    "Parking",
    "King-size bed",
    "Beach access",
    "Suitable for business",
    "Books available",
    "Sound system/stereo",
    "Patio",
    "Water view",
    "Fire extinguisher",
    "Smoke alarm",
    "Bed linen",
    "Towels",
    "High chair",
  ],
  workspace: [
    "High Speed Wifi",
    "Wellness Room",
    "Private Conference Room",
    "Office Supplies",
    "Mail and Packaging",
    "Community Events",
    "Daily Craft Coffee",
    "Parking Space",
    "Dining Options",
    "Cleaning Services",
  ],
};
