export const amenities = [
  "2 Stories",
  "Bike Path",
  "Central Cooling",
  "Central Heating",
  "Cinema",
  "Dual Sinks",
  "Emergency Exit",
  "Fire Alarm",
  "Fire Place",
  "Fitted Kitchen",
  "Gym",
  "Home Theater",
  "Jog Path",
  "Laundry Room",
  "Lawn",
  "Marble Floors ",
  "Wi-Fi",
  "Air Conditioning",
  "Private Pool",
  "Fully Equipped Kitchen",
  "24/7 Security",
  "Parking",
  "Cable TV",
  "Washing Machine",
  "Gym",
  "Terrace with Outdoor Seating   ",
  "Elevator,",
  "24 Hour CCTV Mointoring,",
  "Easy Access from the Bus Stop,",
  "Parking Space Avaliable,",
  "Next to busy way",
  "Room Ensuite",
  "Swimming Pool",
];
